# Generated by Django 5.2.1 on 2025-08-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Projects_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('project_link', models.URLField()),
                ('project_image', models.ImageField(upload_to='my_projects')),
            ],
        ),
    ]
