# Generated by Django 5.2.1 on 2025-08-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects_list',
            name='github_link',
            field=models.URLField(default='not_available'),
        ),
    ]
