# Generated by Django 5.2.1 on 2025-08-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_projects_list_github_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Grade', models.TextField(default='not available')),
                ('course', models.TextField(default='not available')),
                ('year', models.TextField(default='not available')),
                ('university_name', models.TextField(default='not available')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degisnation', models.TextField(default='not available')),
                ('description', models.TextField(default='not available')),
                ('company_name', models.TextField(default='not available')),
            ],
        ),
        migrations.RenameField(
            model_name='personal_info',
            old_name='Designation',
            new_name='Job_role',
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Bi_tools',
            field=models.TextField(default='not available'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Interest',
            field=models.TextField(default='not available'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='Language',
            field=models.TextField(default='english'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='about_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='about_picture',
            field=models.ImageField(default='not available', upload_to='my_projects'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='domain',
            field=models.TextField(default='Retail'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='education',
            field=models.TextField(default='bachelor of Engineering'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='home_picture',
            field=models.ImageField(default='not available', upload_to='my_projects'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='others_skill',
            field=models.TextField(default='not available'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='profile',
            field=models.CharField(default='data science', max_length=200),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='slider_info',
            field=models.TextField(default='not available'),
        ),
        migrations.AddField(
            model_name='projects_list',
            name='project_type',
            field=models.CharField(default='simple'),
        ),
    ]
