# Generated by Django 5.2.1 on 2025-08-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_education_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects_list',
            name='project_bannerdescription',
            field=models.TextField(default='not available'),
        ),
    ]
