# Generated by Django 5.2.1 on 2025-08-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_projects_list_project_bannerdescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.RemoveField(
            model_name='projects_list',
            name='project_type',
        ),
    ]
