# Generated by Django 5.2.1 on 2025-08-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_education_delete_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='Bi_tools',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='Interest',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='about_description',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='about_picture',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='education',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='home_picture',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='others_skill',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='personal_info',
            name='slider_info',
        ),
        migrations.RemoveField(
            model_name='projects_list',
            name='project_bannerdescription',
        ),
        migrations.AddField(
            model_name='personal_info',
            name='reusme',
            field=models.URLField(default='not_available'),
        ),
    ]
