# Generated by Django 5.2.4 on 2025-08-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_personal_info_bi_tools_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_info',
            name='reusme',
        ),
        migrations.AddField(
            model_name='personal_info',
            name='reusme_link',
            field=models.URLField(default='not_available'),
        ),
        migrations.AddField(
            model_name='projects_list',
            name='vedio_link',
            field=models.URLField(default='not available'),
        ),
    ]
