# Generated by Django 5.2.4 on 2025-08-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_personal_info_reusme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='discord_link',
            field=models.URLField(default='https://github.com/MONAlIS-A'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='facebook_link',
            field=models.URLField(default='https://github.com/MONAlIS-A'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='instagram_link',
            field=models.URLField(default='https://github.com/MONAlIS-A'),
        ),
        migrations.AddField(
            model_name='personal_info',
            name='linkedin',
            field=models.URLField(default='https://github.com/MONAlIS-A'),
        ),
    ]
