# Generated by Django 6.0.2 on 2026-05-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_personal_info_discord_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects_list',
            name='category',
            field=models.CharField(choices=[('Backend', 'Backend Projects'), ('Data Engineering', 'Data Engineering Projects'), ('Data Analysis', 'Data Analysis Projects'), ('AI & Machine Learning', 'AI & Machine Learning Projects')], default='Backend', max_length=50),
        ),
        migrations.AddField(
            model_name='projects_list',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
