# Generated by Django 6.0.2 on 2026-05-12 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_projects_list_category_projects_list_sub_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Backend', 'Backend Development'), ('Data Engineering', 'Data Engineering'), ('Data Analysis', 'Data Analysis'), ('AI', 'Data Science & AI')], max_length=50)),
                ('icon_url', models.URLField(blank=True, help_text='URL for the skill icon/logo', null=True)),
                ('details', models.TextField(help_text='Comma-separated focus areas or details')),
            ],
        ),
    ]
