# Generated by Django 6.0.2 on 2026-05-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Backend', 'Backend Tips & Tutorials'), ('Data Engineering', 'Data Engineering Insights'), ('Data Analysis', 'Data Analyst Guides'), ('AI', 'AI & ML Innovations')], max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='URL for the blog category icon/image', null=True)),
                ('link', models.URLField(help_text='Link to the full blog post')),
                ('summary_points', models.TextField(help_text='Comma-separated summary points or highlights')),
            ],
        ),
    ]
