# Generated by Django 6.0.5 on 2026-05-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='github_link',
            field=models.URLField(default='https://github.com/'),
        ),
    ]
